# Generated by Django 4.2.20 on 2025-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('stock_code', models.TextField()),
                ('comments', models.TextField()),
                ('save_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
